import type { Metadata } from "next";
import { ubuntu } from "@/@types/font/Font";
import "./globals.css";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={ubuntu.className}>{children}</body>
		</html>
	);
}
